### ISSUE TITLE
인증 방법

### ISSUE THREAD

**Issue by wonhajiyo** [HwangWonYo/flask-clova#5]
개발에 뛰어든지 얼마 안된 사람입니다.

코드를 살펴보던 중 app.confing 부분이 잘 못 되어 있는거 같은데 app.config 맞나요?

그리고 클로바 스피커랑 연동하려고 하는데 인증 부분을 어떻게 해결하는 건지 모르겠습니다.
도움말이 잘 안되어 있어서 설명 좀 부탁드려요

**Comment by HwangWonYo** [comment]
안녕하세요.

app.config라고 해야하는데 confing라고 되어있으면 오류입니다.
ReadMe.md에 제가 잘못 적었네요. 곧바로 수정하겠습니다.

인증 부분이라고 하면 어떤 부분을 말씀하시는거죠?

**Comment by wonhajiyo** [comment]
https://youtu.be/WYYxafb1A6E?t=600 보시면 Flask-ASK에서 ngrok 통해서 아마존에 URL 적는 부분이 있는게 그것에 상응하는게 무엇인지 궁금해서 물어본 것이였습니다.
CEK 페이지 링크좀 알려주세요

**Comment by HwangWonYo** [comment]
https://developers.naver.com/console/clova/
cek 콘솔은 이곳입니다.

인증부분 질문은 아직도 이해가 안되네요;;

**Comment by wonhajiyo** [comment]
test_sample.py를 참조하여 POST로 요청 보낼 때 아래와 같이 보내서 응답이 오는 것 까지 확인은 했습니다.

{
  "version": "0.1.0",
  "session": {
    "new": "False",
    "sessionAttributes": {},
    "sessionId": "a29cfead-c5ba-474d-8745-6c1a6625f0c5",
    "user": {
      "userId": "V0qe",
      "accessToken": "XHapQasdfsdfFsdfasdflQQ7"
    }
  },


궁금한 것은 
sessionId, userId, accessToken 같은게 있는데 이거를 따로 인증받아서 하는 건가요?
아니면 그냥 저걸로 쓰면 되는건가요?

제 클로바 스피커에 서비스 응답이 나오게 하고 싶은데 sessionId, userId, accessToken를 제가 따로 발급받아서 써야되는건가요?

**Comment by HwangWonYo** [comment]
제가 직접 만들어 볼때는 따로 발급받지 않았습니다.
위 정보는 CEK가 서버에 POST를 전달할때 같이 옵니다.
직접 음성앱을 만드실 때는 고려하실 필요 없을거에요.

저는 이렇게 이해하고 있는데
만약에 아니라면 코멘트 또 남겨주세요 :)
