### ISSUE TITLE
Method Not Allowed (405 Error)

### ISSUE THREAD

**Issue by wonhajiyo** [HwangWonYo/flask-clova#6]
README.md에 있는 Basic  보고 따라하는데 http://127.0.0.1:5000을 호출하면 계속 Method Not Allowed (405 Error) 에러가 뜹니다.
해결방법 좀 알려주세요.
그리고 코드에 app.run(port='5000' 에 적혀있는데
5000은 숫자형식으로 적는게 맞지 않나 싶어요. app.run(port=5000

**Comment by HwangWonYo** [comment]
그렇네요. port=5000 이 맞겠네요

Basic을 따라하시는 거라면 endpoint가 http://127.0.0.1:5000/user_defined에 post로 request를 보내셔야합니다. 
http://127.0.0.1:5000/를 브라우저 창에 입력하셨다면 해당 uri 및 메서드에 대한 처리를 하지 않았기 때문에 405 에러가 나타납니다.
CEK는 post로만 요청을 보내기 때문에 get 요청은 배제했습니다.

만약 / 로 get 요청을 보내고 싶으시면
flask 웹앱을 만들때처럼 설정해주시면 됩니다.
즉, 아래의 코드가 추가되어야 합니다.
```python
@app.route('/', methods=['GET'])
def function_name():
    pass
```
