### ISSUE TITLE
멀티턴의 경우 어떻게 구현할 수 있을까요?

### ISSUE THREAD

**Issue by bzantium** [HwangWonYo/flask-clova#8]
멀티턴의 경우 어떻게 구현할 수 있을까요?

**Comment by HwangWonYo** [comment]
[/samples/session](https://github.com/HwangWonYo/flask-clova/blob/master/samples/session/session.py) 부분의 예제를 참고해보세요.

현재 턴의 정보를 session.attribute 에 전달하면
CEK가 다음턴에 그대로 전달해줍니다.
이 값을 이용해서 멀티턴을 해결하는 방법 말고는 아이디어가 없네요..ㅎㅎ

예: 
```
# 첫번째 발화
>> user: 나는 노란색을 제일 좋아해.
>> bot: 그렇구나
# 두번째 발화
>> user: 내가 무슨 색이라고?
>> bot: 노란색
```

sample 코드와 다른 예시인데 이런식으로 멀티턴을 진행할 수 있습니다.
첫번째 발화에서 말한 색을 session attribute에 담고 있다가
두번째 발화에서 그 값을 사용하는 방법입니다.

**Comment by Bricoler** [comment]
감사합니다! 한 가지 더 여쭤볼게요~!
