### ISSUE TITLE
flask_clova를 aws lambda 를 이용해서 구동할 수 있을까요?

### ISSUE THREAD

**Issue by bzantium** [HwangWonYo/flask-clova#9]
flask_clova를 aws lambda 를 이용해서 구동할 수 있을까요? 코드 중간에 api 호출 같은 기능도 있습니다. aws lambda 서버를 사용해보지 않아서 혹시 가능할 지 여쭤보고 싶습니다. 감사합니다!

**Comment by HwangWonYo** [comment]
완전 가능합니다 ㅎㅎ
aws lambda 서비스는 serverless 서비스인데 빠르게 껏다 켜는 컴퓨터(?)라고 이해하면 쉬울거 같아요.
단점은 serverless 서비스이기에 자체적인 session을 활용할 수 없지만 cek가 주는 sessionAttribute를 사용하면 되니까 문제 없을거 같습니다.
aws lambda로 하면 ssl 같은 인증도 따로 할 필요 없습니다.

**Comment by Bricoler** [comment]
감사합니다! 혹시 도메인 이름도 계속 유지 되는건가요? (cek 등록때문에...)
